In [1]:
import Bio
import json
import requests
import pandas as pd
from Bio.SeqUtils.ProtParam import ProteinAnalysis

#### Combining Dataframes
+ pd.concat([df1, df4], axis=1)

+ pd.concat([df1, df2], axis=1)

In [4]:
liz_data = pd.read_csv('Disprot_sequence.csv') 
liz_data['seq_len'] = liz_data['sequence'].apply(len)
liz_clean_col= liz_data.drop(['uniref50'], axis=1)

liz_clean_col.loc[:,'disorder'] = 1
liz_clean_col

                                               sequence  seq_len  disorder
0     MASREEEQRETTPERGRGAARRPPTMEDVSSPSPSPPPPRAPPKKR...      529         1
1     MKTQRDGHSLGRWSLVLLLLGLVMPLAIIAQVLSYKEAVLRAIDGI...      170         1
2     MDAQTRRRERRAEKQAQWKAANPLLVGVSAKPVNRPILSLNRKPKS...      107         1
3     MGDVEKGKKIFVQKCAQCHTVEKGGKHKTGPNLHGLFGRKTGQAPG...      105         1
4     MPKRGKKGAVAEDGDELRTEPEAKKSKTAAKKNDKEAAGEGPALYE...      318         1
...                                                 ...      ...       ...
2361  MSLLTEVETYVLSIIPSGPLKAEIAQRLEDVFAGKNTDLEVLMEWL...      252         1
2362  MDVNPTLLFLKVPAQNAISTTFPYTGDPPYSHGTGTGYTMDTVNRT...      757         1
2363  MATKGTKRSYEQMETDGERQNATEIRASVGKMIDGIGRFYIQMCTE...      498         1
2364  MDPNTVSSFQVDCFLWHVRKRVADQELGDAPFLDRLRRDQKSLRGR...      230         1
2365  MNPNQKIITIGSVCMTIGMANLILQIGNIISIWISHSIQLGNQNQI...      469         1

[2366 rows x 3 columns]

In [5]:
liz_clean_col.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2366 entries, 0 to 2365
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sequence  2366 non-null   object
 1   seq_len   2366 non-null   int64
 2   disorder  2366 non-null   int64
dtypes: int64(2), object(1)
memory usage: 55.6+ KB

In [8]:
michelle_data = pd.read_csv("./structured.csv")
michelle_data[:10]

                                            prot_seq  seq_len rcsb_id
0  SGEAPNQALLRILKETEFKKIKVLGSGAFGTVYKGLWIPEGEKVKI...      328    6V5P
1  EADCGLRPLFEKKSLEDKTERELLESYIDGRIVEGSDAEIGMSPWQ...      290    6V5T
2  SNAQSEQSTHIEGVAEKPVEFVKLGTGVWMHTGYKVVPPWGNIRTN...      235    6V61
3                            TLKYPIEKGIVTNWDDMEKIWHH       23    6V62
4  GSMGKKSRVKTQKSGTGATATVSPKEILNLTSELLQKCSSPAPGPG...      596    6V62
5                            TLKYPIEQGIVTNWDDMEKIWHH       23    6V63
6  GSMGKKSRVKTQKSGTGATATVSPKEILNLTSELLQKCSSPAPGPG...      596    6V63
7                     ADCGLRPLFEKKSLEDKTERELLESYIDGR       30    6V64
8  IVEGSDAEIGMSPWQVMLFRKSPQELLCGASLISDRWVLTAAHCLL...      259    6V64
9  SYARVRAVVMTRDDSSGGWLPLGGSGLSSVTVFKVPHQEENGCADF...      113    6V65

In [9]:
import csv

with open('rcsb_disordered.csv', 'r') as read_obj:
    csv_reader = csv.reader(read_obj)
    lst_rcsb_id = list(csv_reader)

disordered = lst_rcsb_id[0]

michelle_data["rcsb_id"] = michelle_data["rcsb_id"].astype(str)
df_disordered = michelle_data.loc[michelle_data["rcsb_id"].isin(disordered)]
df_ordered = michelle_data[michelle_data.rcsb_id.isin(disordered) == False]

# define a new column and assign values according to their presence in the list above 
df_disordered["label"] = 1 
df_ordered["label"] = 0 
merge = pd.concat([df_ordered, df_disordered])
michelle_data = merge.drop(columns = ["seq_len", "rcsb_id"])
michelle_data = michelle_data.rename(columns={"prot_seq":"sequence"}, errors = "raise")

/Users/michellegarcia/miniconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/michellegarcia/miniconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [10]:
ulas_data = pd.read_csv("./Ulas_data.csv")
ulas_data = ulas_data.drop(columns=["Unnamed: 0"])
ulas_data["label"] = 1

In [11]:
liz_clean_col = liz_clean_col.drop(columns="seq_len")

In [12]:
liz_clean_col = liz_clean_col.rename(columns={"disorder":"label"})
liz_clean_col.head()

                                            sequence  label
0  MASREEEQRETTPERGRGAARRPPTMEDVSSPSPSPPPPRAPPKKR...      1
1  MKTQRDGHSLGRWSLVLLLLGLVMPLAIIAQVLSYKEAVLRAIDGI...      1
2  MDAQTRRRERRAEKQAQWKAANPLLVGVSAKPVNRPILSLNRKPKS...      1
3  MGDVEKGKKIFVQKCAQCHTVEKGGKHKTGPNLHGLFGRKTGQAPG...      1
4  MPKRGKKGAVAEDGDELRTEPEAKKSKTAAKKNDKEAAGEGPALYE...      1

In [13]:
prot_seq = pd.concat([liz_clean_col, michelle_data, ulas_data], ignore_index=True)
prot_seq.head()

                                            sequence  label
0  MASREEEQRETTPERGRGAARRPPTMEDVSSPSPSPPPPRAPPKKR...      1
1  MKTQRDGHSLGRWSLVLLLLGLVMPLAIIAQVLSYKEAVLRAIDGI...      1
2  MDAQTRRRERRAEKQAQWKAANPLLVGVSAKPVNRPILSLNRKPKS...      1
3  MGDVEKGKKIFVQKCAQCHTVEKGGKHKTGPNLHGLFGRKTGQAPG...      1
4  MPKRGKKGAVAEDGDELRTEPEAKKSKTAAKKNDKEAAGEGPALYE...      1

In [14]:
# list of all labels 
labels = prot_seq["label"]

In [5]:
#michelle_clean_col = michelle_data.rename(columns = {"prot_seq":"sequence"})
#mich_clean_col = michelle_clean_col.drop(['rcsb_id'], axis=1)
#mich_clean_col

                                                 sequence  seq_len
0       SGEAPNQALLRILKETEFKKIKVLGSGAFGTVYKGLWIPEGEKVKI...      328
1       EADCGLRPLFEKKSLEDKTERELLESYIDGRIVEGSDAEIGMSPWQ...      290
2       SNAQSEQSTHIEGVAEKPVEFVKLGTGVWMHTGYKVVPPWGNIRTN...      235
3                                 TLKYPIEKGIVTNWDDMEKIWHH       23
4       GSMGKKSRVKTQKSGTGATATVSPKEILNLTSELLQKCSSPAPGPG...      596
...                                                   ...      ...
249803  MARGKAKEEGSWKKFIWNSEKKEFLGRTGGSWFKILLFYVIFYGCL...      303
249804  MAGLSTDDGGSPKGDVDPFYYDYETVRNGGLIFAALAFIVGLIIIL...       65
249805  GRDKYEPAAVSEHGDKKKAKKERDMDELKKEVSMDDHKLSLDELHR...     1016
249806  MARGKAKEEGSWKKFIWNSEKKEFLGRTGGSWFKILLFYVIFYGCL...      303
249807  MAGLSTDDGGSPKGDVDPFYYDYETVRNGGLIFAALAFIVGLIIIL...       65

[249808 rows x 2 columns]

In [14]:
# adding both liz's and michelle's data 
#prot_seq = pd.concat([liz_clean_col, mich_clean_col], ignore_index=True)
#prot_seq

                                                 sequence  label
0       MASREEEQRETTPERGRGAARRPPTMEDVSSPSPSPPPPRAPPKKR...      1
1       MKTQRDGHSLGRWSLVLLLLGLVMPLAIIAQVLSYKEAVLRAIDGI...      1
2       MDAQTRRRERRAEKQAQWKAANPLLVGVSAKPVNRPILSLNRKPKS...      1
3       MGDVEKGKKIFVQKCAQCHTVEKGGKHKTGPNLHGLFGRKTGQAPG...      1
4       MPKRGKKGAVAEDGDELRTEPEAKKSKTAAKKNDKEAAGEGPALYE...      1
...                                                   ...    ...
257548  MYIEEIILDGFKSYPTKTVIGPFHPQFNAITGLNGSGKSNVLDAIC...      1
257549  MYIKQIRLKGFRTYKNETTIDFTRGINCIVGFNGSGKSNILLAIEF...      1
257550  MVITLPKLKYALNALSPHISEETLNFHYNKHHAGYVNKLNTLIKDT...      1
257551  MMLNKKVVALCTLTLHLFCIFLCLGKEVRSEENGKIQDDAKKIVSE...      1
257552  MLNIIYVVSLILIKFIFYKECNNNNNYYLSNIELYNYKLRKRNRIL...      1

[257553 rows x 2 columns]

In [15]:
# wow that's a big dataset 
prot_seq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257553 entries, 0 to 257552
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   sequence  257553 non-null  object
 1   label     257553 non-null  int64
dtypes: int64(1), object(1)
memory usage: 3.9+ MB

#### Cleaning and Preparing the Data
+ removing invalid AAs
+ adding characteristics

In [16]:
import re
def clean_prot(line):
    """ cleaning AAs by removing invalid AA's
    """
        
    # remove here 
    line = re.sub("U", "", line)
    line = re.sub("X", "", line)
    line = re.sub("J", "", line)
    line = re.sub("U", "", line)
    line = re.sub("O", "", line)
    
    # replace here
    line = re.sub("Z", "Q", line)
    line = re.sub("B", "N", line)
    
    return line

X = "MDSVYVDIDADSAFLKALQRAYPMFEVEPRQVTSNDHANARAFSHLAIKLIEQEIDPDSTILDIGSAPARRMMSDRKYHCVCPMRSAEDPERLANYARKLASAAGKVLDRNISGKIGDLQAVMAVPDTETPTFCLHTDVSCRQRADVAIYQDVYAVHAPTSLYHQAIKGVRVAYWVGFDTTPFMYNAMAGAYPSYSTNWADEQVLKAKNIGLCSTDLTEGRRGKLSIMRGKKLKPCDRVLFSVGSTLYPESRTLLKSWHLPSVFHLKGKLSFTCRCDTVVSCEGYVVKRITMSPGLYGKTIGYAVTHHADGFLMCKTTDTVDGERVSFSVCTYVPATICDQMTGILATEVTPEDAQKLLVGLNQRIVVNGRTQRNTNTMKNYLLPVVAQAFSKWAKECRKDMEDEKLLGVRERTLTCCCLWAFKKQKTHTVYKRPDTQSIQKVQAEFDSFVVPGLWSSGLSIPLRTRIKWLLRKVPKTDLIPYSGNAQEAQDAEKEAEEEREAELTHEALPPLQAAQEDVQVEIDVEQLEDRAGAGIIETPRGAIKVTAQLTDHVVGEYLVLSPQTVLRSQKLSLIHALAEQVKTCTHSGRAGRYAVEAYDGRVLVPSGYAISPEDFQSLSESATMVYNEREFVNRKLHHIAMHGPALNTDEESYELVRAERTEHEYVYDVDQRRCCKKEEAAGLVLVGDLTNPPYHEFAYEGLKIRPACPYKIAVIGVFGVPGSGKSAIIKNLVTRQDLVTSGKKENCQEISTDVMRQRGLEISARTVDSLLLNGCNRPVDVLYVDEAFACHSGTLLALIALVRPRQKVVLCGDPKQCGFFNMMQMKVNYNHNICTQVYHKSISRRCTLPVTAIVSSLHYEGKMRTTNEYNMPIVVDTTGSTKPDPGDLVLTCFRGWVKQLQIDYRGHEVMTAAASQGLTRKGVYAVRQKVNENPLYASTSEHVNVLLTRTEGKLVWKTLSGDPWIKTLQNPPKGNFKATIKEWEVEHASIMAGICSHQVTFDTFQNKANVCWAKSLVPILETAGIKLNDRQWSQIIQAFKEDKAYSPEVALNEICTRMYGVDLDSGLFSKPLVSVYYADNHWDNRPGGKMFGFNPEAASILERKYPFTKGKWNINKQICVTTRRIEDFNPTTNIIPVNRRLPHSLVAEHRPVKGERMEWLVNKINGHHVLLVSGYNLALPTKRVTWVAPLGVRGADYTYNLELGLPATLGRYDLVVINIHTPFRIHHYQQCVDHAMKLQMLGGDSLRLLKPGGSLLIRAYGYADRTSERVICVLGRKFRSSRALKPPCVTSNTEMFFLFSNFDNGRRNFTTHVMNNQLNAAFVGQATRAGCAPSYRVKRMDIAKNDEECVVNAANPRGLPGDGVCKAVYKKWPESFKNSATPVGTAKTVMCGTYPVIHAVGPNFSNYSESEGDRELAAAYREVAKEVTRLGVNSVAIPLLSTGVYSGGKDRLTQSLNHLFTAMDSTDADVVIYCRDKEWEKKISEAIQMRTQVELLDEHISIDCDVIRVHPDSSLAGRKGYSTTEGALYSYLEGTRFHQTAVDMAEIYTMWPKQTEANEQVCLYALGESIESIRQKCPVDDADASSPPKTVPCLCRYAMTPERVTRLRMNHVTNIIVCSSFPLPKYKIEGVQKVKCSKVMLFDHNVPSRVSPREYRSSQESVQEVSTTTSLTHSQFDLSADGETLPVPSDLDADAPALEPALDDGAVHTLPTIIGNLAAVSDWVMSTVPVAPPRRRRGRNLTVTCDEREGNITPMASVRFFRAELCPAVQETAETRDTAISLQAPPSTTMELSHPPISFGAPSETFPITFGDFDEGEIESLSSELLTFGDFLPGEVDDLTDSDWSTCPDTDDELXLDRAGGYIFSSDTGPGHLQQKSVRQSVLPVNTLEEVHEEKCYPPKLDELKEQLLLKKLQESASMANRSRYQSRKVENMKATIIQRLKRGCKLYLMAETPKVPTYRTIYPAPVYSPPINVRLSNPESAVAACNEFLARNYPTVSSYQITDEYDAYLDMVDGSESCLDRATFNPSKLRSYPKQHAYHAPSIRSAVPSPFQNTLQNVLAAATKRNCNVTQMRELPTLDSAVFNVECFKKFACNREYWEEFAASPIRITTENLTTYVTKLKGPKAAALFAKTHNLLPLQDVPMDRFTVDMKRDVKVTPGTKHTEERPKVQVIQAAEPLATAYLCGIHRELVRRLNAVLLPNVHTLFDMSAEDFDAIIAAHFKPGDAVLETDIASFDKSQDDSLALTALMLLEDLGVDHSLLDLIEAAFGEISSCHLPTGTRFKFGAMMKSGMFLTLFVNTLLNITIASRVLEDRLTKSACAAFIGDDNIIHGVVSDELMAARCATWMNMEVKIIDAVVSQKAPYFCGGFILHDTVTGTACRVADPLKRLFKLGKPLAAGDEQDEDRRRALADEVIRWQRTGLIDELEKAVYSRYEVQGISVAVMSMATFASSRSNFEKLRGPVITLYGGPK"
X_X = "JJJMDSVYVXXXDIDADSAZZQQFLKAXLQRAYPM"
X_clean = clean_prot(X)
X_Xclean = clean_prot(X_X)

In [17]:
# replacing all instances of X in AA sequences
seq_with_X = prot_seq['sequence'].apply(clean_prot)
df_clean = seq_with_X.to_frame() 
df_clean['sequence']

# non in place (keeps original index)
df_clean_fin = df_clean.loc[df_clean['sequence'] != '']
df_clean_fin
# inplace drop of columns (resassign index)
# df_clean_fin = df_clean.drop(df_clean.loc[df_clean['sequence'] == ''].index, inplace = True) #251418

                                                 sequence
0       MASREEEQRETTPERGRGAARRPPTMEDVSSPSPSPPPPRAPPKKR...
1       MKTQRDGHSLGRWSLVLLLLGLVMPLAIIAQVLSYKEAVLRAIDGI...
2       MDAQTRRRERRAEKQAQWKAANPLLVGVSAKPVNRPILSLNRKPKS...
3       MGDVEKGKKIFVQKCAQCHTVEKGGKHKTGPNLHGLFGRKTGQAPG...
4       MPKRGKKGAVAEDGDELRTEPEAKKSKTAAKKNDKEAAGEGPALYE...
...                                                   ...
257548  MYIEEIILDGFKSYPTKTVIGPFHPQFNAITGLNGSGKSNVLDAIC...
257549  MYIKQIRLKGFRTYKNETTIDFTRGINCIVGFNGSGKSNILLAIEF...
257550  MVITLPKLKYALNALSPHISEETLNFHYNKHHAGYVNKLNTLIKDT...
257551  MMLNKKVVALCTLTLHLFCIFLCLGKEVRSEENGKIQDDAKKIVSE...
257552  MLNIIYVVSLILIKFIFYKECNNNNNYYLSNIELYNYKLRKRNRIL...

[256797 rows x 1 columns]

In [18]:
# get new labels based off filtering
indices = df_clean_fin.index.to_list()
labels = labels.iloc[indices].to_list()

In [19]:
print(len(labels))

256797

In [20]:
""" testing if the replace_X function works in clearing out unambiguous AAs (X)
"""
X = X_Xclean
no_X = "MASVHESLYFNPMMTNGVVHANVFGIKDWVT"

analyze_protX = ProteinAnalysis(X)
analyze_prot_no = ProteinAnalysis(no_X)

count1 = analyze_protX.count_amino_acids()['A']
count2= analyze_prot_no.count_amino_acids()['A']

print(f"analyze_protX {count1} | analyze_prot_no {count2}")


count1 = analyze_protX.molecular_weight()
count2= analyze_prot_no.molecular_weight()

print(f"analyze_protX has a molecular weight of {count1} \nanalyze_prot_no has a molecular weight of {count2}")

analyze_protX 4 | analyze_prot_no 2
analyze_protX has a molecular weight of 3232.5972999999994
analyze_prot_no has a molecular weight of 3496.0002999999997

In [23]:
# creating a csv with no characteristics
# note: the index with removed rows is not within set
df_clean_fin.to_csv('michelle_liz_ulas_data_noChar.csv')

#### Analyzing the AA Sequences & Adding additional Characteristics
 <a ref = https://biopython.org/wiki/ProtParam read more about functions used here \>
+ molecular weight | prot.molecular_weight()
+ hydrophobicity | prot.gravy()

In [21]:
# applying the Protein Analysis function of BioPython to convert
# amino acids to be evaluated though built in functions (molecular weight)
analyze_prot = df_clean_fin["sequence"].apply(ProteinAnalysis)

In [22]:
# GOOD LUCK :D
list(analyze_prot)[0].count_amino_acids()['A']

47

In [23]:
# testing to see if molecular weight is working on a smaller dataset
list_prot = list(analyze_prot[:10])
molecular_w = [x.molecular_weight() for x in list_prot]
merge_list = tuple(zip(list(prot_seq["sequence"][:10]), molecular_w))
merge_list

(('MASREEEQRETTPERGRGAARRPPTMEDVSSPSPSPPPPRAPPKKRMRRRIESEDEEDSSQDALVPRTPSPRPSTSAADLAIAPKKKKKRPSPKPERPPSPEVIVDSEEEREDVALQMVGFSNPPVLIKHGKGGKRTVRRLNEDDPVARGMRTQEEEEEPSEAESEITVMNPLSVPIVSAWEKGMEAARALMDKYHVDNDLKANFKLLPDQVEALAAVCKTWLNEEHRGLQLTFTSKKTFVTMMGRFLQAYLQSFAEVTYKHHEPTGCALWLHRCAEIEGELKCLHGSIMINKEHVIEMDVTSENGQRALKEQSSKAKIVKNRWGRNVVQISNTDARCCVHDAACPANQFSGKSCGMFFSEGAKAQVAFKQIKAFMQALYPNAQTGHGHLLMPLRCECNSKPGHAPFLGRQLPKLTPFALSNAEDLDADLISDKSVLASVHHPALIVFQCCNPVYRNSRAQGGGPNCDFKISAPDLLNALVMVRSLWSENFTELPRMVVPEFKWSTKHQYRNVSLPVAHSDARQNPFDF',
  59138.73500000009),
 ('MKTQRDGHSLGRWSLVLLLLGLVMPLAIIAQVLSYKEAVLRAIDGINQRSSDANLYRLLDLDPRPTMDGDPDTPKPVSFTVKETVCPRTTQQSPEDCDFKKDGLVKRCMGTVTLNQARGSFDISCDKDNKRFALLGDFFRKSKEKIGKEFKRIVQRIKDFLRNLVPRTES',
  19301.1649),
 ('MDAQTRRRERRAEKQAQWKAANPLLVGVSAKPVNRPILSLNRKPKSRVESALNPIDLTVLAEYHKQIESNLQRIERKNQRTWYSKPGERGITCSGRQKIKGKSIPLI',
  12298.116199999986),
 ('MGDVEKGKKIFVQKCAQCHTVEKGGKHKTGPNLHGLFGRKTGQAPGFTYTDANKNKGITWKEETLMEYLENPKKYIPGTKMIFAGIKKKTEREDLIAYLKKATNE',
  11832.605799999988),
 ('MPKRGKKGAVAEDGDELRTEPEAKKSKTAAKKNDKEAAGEGPALYEDPPDQKTSPSGKPATLKICSWNVDGLRAWIKKKGLDWVKEEAPDILCLQETKCSENKLPAELQELPGLSHQYWSAPSDKEGYSGVGLLSRQCPLKVSYGIGDEEHDQEGRVIVAEFDSFVLVTAYVPNAGRGLVRLEYRQRWDEAFRKFLKGLASRKPLVLCGDLNVAHEEIDLRNPKGNKKNAGFTPQERQGFGELLQAVPLADSFRHLYPNTPYAYTFWTYMMNARSKNVGWRLDYFLLSHSLLPALCDSKIRSKALGSDHCPITLYLAL',
  35554.073000000004),
 ('MLWQKSTAPEQAPAPPRPYQGVRVKEPVKELLRRKRGHTSVGAAGPPTAVVLPHQPLATYSTVGPSCLDMEVSASTVTEEGTLCAGWLSQPAPATLQPLAPWTPYTEYVSHEAVSCPYSTDMYVQPVCPSYTVVGPSSVLTYASPPLITNVTPRSTATPAVGPQLEGPEHQAPLTYFPWPQPLSTLPTSSLQYQPPAPTLSGPQFVQLPISIPEPVLQDMDDPRRAISSLTIDKLLLEEEESNTYELNHTLSVEGF',
  27692.066700000014),
 ('MAVPGYYELYRRSTIGNSLVDALDTLISDGRIEASLAMRVLETFDKVVAETLKDNTQSKLTVKGNLDTYGFCDDVWTFIVKNCQVTVEDSHRDASQNGSGDSQSVISVDKLRIVACNSKKSE',
  13457.941399999987),
 ('MELIQDTSRPPLEYVKGVPLIKYFAEALGPLQSFQARPDDLLINTYPKSGTTWVSQILDMIYQGGDLEKCNRAPIYVRVPFLEVNDPGEPSGLETLKDTPPPRLIKSHLPLALLPQTLLDQKVKVVYVARNPKDVAVSYYHFHRMEKAHPEPGTWDSFLEKFMAGEVSYGSWYQHVQEWWELSRTHPVLYLFYEDMKENPKREIQKILEFVGRSLPEETMDFMVQHTSFKEMKKNPMTNYTTVPQELMDHSISPFMRKGMAGDWKTTFTVAQNERFDADYAEKMAGCSLSFRSEL',
  34195.78490000006),
 ('MQRSPLEKASVVSKLFFSWTRPILRKGYRQRLELSDIYQIPSVDSADNLSEKLEREWDRELASKKNPKLINALRRCFFWRFMFYGIFLYLGEVTKAVQPLLLGRIIASYDPDNKEERSIAIYLGIGLCLLFIVRTLLLHPAIFGLHHIGMQMRIAMFSLIYKKTLKLSSRVLDKISIGQLVSLLSNNLNKFDEGLALAHFVWIAPLQVALLMGLIWELLQASAFCGLGFLIVLALFQAGLGRMMMKYRDQRAGKISERLVITSEMIENIQSVKAYCWEEAMEKMIENLRQTELKLTRKAAYVRYFNSSAFFFSGFFVVFLSVLPYALIKGIILRKIFTTISFCIVLRMAVTRQFPWAVQTWYDSLGAINKIQDFLQKQEYKTLEYNLTTTEVVMENVTAFWEEGFGELFEKAKQNNNNRKTSNGDDSLFFSNFSLLGTPVLKDINFKIERGQLLAVAGSTGAGKTSLLMVIMGELEPSEGKIKHSGRISFCSQFSWIMPGTIKENIIFGVSYDEYRYRSVIKACQLEEDISKFAEKDNIVLGEGGITLSGGQRARISLARAVYKDADLYLLDSPFGYLDVLTEKEIFESCVCKLMANKTRILVTSKMEHLKKADKILILHEGSSYFYGTFSELQNLQPDFSSKLMGCDSFDQFSAERRNSILTETLHRFSLEGDAPVSWTETKKQSFKQTGEFGEKRKNSILNPINSIRKFSIVQKTPLQMNGIEEDSDEPLERRLSLVPDSEQGEAILPRISVISTGPTLQARRRQSVLNLMTHSVNQGQNIHRKTTASTRKVSLAPQANLTELDIYSRRLSQETGLEISEEINEEDLKECFFDDMESIPAVTTWNTYLRYITVHKSLIFVLIWCLVIFLAEVAASLVVLWLLGNTPLQDKGNSTHSRNNSYAVIITSTSSYYVFYIYVGVADTLLAMGFFRGLPLVHTLITVSKILHHKMLHSVLQAPMSTLNTLKAGGILNRFSKDIAILDDLLPLTIFDFIQLLLIVIGAIAVVAVLQPYIFVATVPVIVAFIMLRAYFLQTSQQLKQLESEGRSPIFTHLVTSLKGLWTLRAFGRQPYFETLFHKALNLHTANWFLYLSTLRWFQMRIEMIFVIFFIAVTFISILTTGEGEGRVGIILTLAMNIMSTLQWAVNSSIDVDSLMRSVSRVFKFIDMPTEGKPTKSTKPYKNGQLSKVMIIENSHVKKDDIWPSGGQMTVKDLTAKYTEGGNAILENISFSISPGQRVGLLGRTGSGKSTLLSAFLRLLNTEGEIQIDGVSWDSITLQQWRKAFGVIPQKVFIFSGTFRKNLDPYEQWSDQEIWKVADEVGLRSVIEQFPGKLDFVLVDGGCVLSHGHKQLMCLARSVLSKAKILLLDEPSAHLDPVTYQIIRRTLKQAFADCTVILCEHRIEAMLECQQFLVIEENKVRQYDSIQKLLNERSLFRQAISPSDRVKLFPHRNSSKCKSKPQIAALKEETEEEVQDTRL',
  168139.53060000026),
 ('MEMFQGLLLLLLLSMGGTWASKEPLRPRCRPINATLAVEKEGCPVCITVNTTICAGYCPTMTRVLQGVLPALPQVVCNYRDVRFESIRLPGCPRGVNPVVSYAVALSCQCALCRRSTTDCGGPKDHPLTCDDPRFQDSSSSKAPPPSLPSPSRLPGPSDTPILPQ',
  17738.568599999977))

In [24]:
list_prot = list(analyze_prot)

df_prot_char = df_clean_fin.copy()
df_prot_char["seq_len"] = df_clean_fin['sequence'].apply(len) 
df_prot_char["molecular_weight"] = [x.molecular_weight() for x in list_prot]
df_prot_char

,sequence,seq_len,molecular_weight
0,MASREEEQRETTPERGRGAARRPPTMEDVSSPSPSPPPPRAPPKKR...,529,59138.7350
1,MKTQRDGHSLGRWSLVLLLLGLVMPLAIIAQVLSYKEAVLRAIDGI...,170,19301.1649
2,MDAQTRRRERRAEKQAQWKAANPLLVGVSAKPVNRPILSLNRKPKS...,107,12298.1162
3,MGDVEKGKKIFVQKCAQCHTVEKGGKHKTGPNLHGLFGRKTGQAPG...,105,11832.6058
4,MPKRGKKGAVAEDGDELRTEPEAKKSKTAAKKNDKEAAGEGPALYE...,318,35554.0730
...,...,...,...
257548,MYIEEIILDGFKSYPTKTVIGPFHPQFNAITGLNGSGKSNVLDAIC...,1218,143057.5679
257549,MYIKQIRLKGFRTYKNETTIDFTRGINCIVGFNGSGKSNILLAIEF...,1193,141223.7597
257550,MVITLPKLKYALNALSPHISEETLNFHYNKHHAGYVNKLNTLIKDT...,198,22733.3478
257551,MMLNKKVVALCTLTLHLFCIFLCLGKEVRSEENGKIQDDAKKIVSE...,688,77645.7201
257552,MLNIIYVVSLILIKFIFYKECNNNNNYYLSNIELYNYKLRKRNRIL...,1341,154797.7810

In [25]:
df_prot_char["hydrophobicity" ] = [x.gravy() for x in list_prot]
df_prot_char["instability_index"] = [x.instability_index() for x in list_prot]
df_prot_char["aromaticity"] = [x.aromaticity() for x in list_prot]

In [26]:
aa = ["A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y"]

In [27]:
for a in aa: 
    l = a + " %"
    df_prot_char[l] = [x.get_amino_acids_percent()[a] for x in list_prot]
df_prot_char

,sequence,seq_len,molecular_weight,hydrophobicity,instability_index,aromaticity,A %,C %,D %,E %,...,M %,N %,P %,Q %,R %,S %,T %,V %,W %,Y %
0,MASREEEQRETTPERGRGAARRPPTMEDVSSPSPSPPPPRAPPKKR...,529,59138.7350,-0.611153,58.945936,0.058601,0.088847,0.024575,0.045369,0.085066,...,0.032136,0.041588,0.085066,0.039698,0.069943,0.077505,0.039698,0.064272,0.011342,0.011342
1,MKTQRDGHSLGRWSLVLLLLGLVMPLAIIAQVLSYKEAVLRAIDGI...,170,19301.1649,-0.441765,37.586471,0.064706,0.041176,0.023529,0.094118,0.035294,...,0.023529,0.029412,0.052941,0.041176,0.088235,0.064706,0.058824,0.064706,0.005882,0.011765
2,MDAQTRRRERRAEKQAQWKAANPLLVGVSAKPVNRPILSLNRKPKS...,107,12298.1162,-0.919626,46.321495,0.037383,0.074766,0.009346,0.018692,0.065421,...,0.009346,0.056075,0.065421,0.065421,0.121495,0.074766,0.037383,0.046729,0.018692,0.018692
3,MGDVEKGKKIFVQKCAQCHTVEKGGKHKTGPNLHGLFGRKTGQAPG...,105,11832.6058,-0.875238,15.507619,0.085714,0.057143,0.019048,0.028571,0.085714,...,0.028571,0.047619,0.038095,0.028571,0.019048,0.000000,0.095238,0.028571,0.009524,0.038095
4,MPKRGKKGAVAEDGDELRTEPEAKKSKTAAKKNDKEAAGEGPALYE...,318,35554.0730,-0.583019,43.411950,0.088050,0.084906,0.022013,0.059748,0.075472,...,0.009434,0.034591,0.066038,0.031447,0.053459,0.062893,0.034591,0.047170,0.022013,0.037736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257548,MYIEEIILDGFKSYPTKTVIGPFHPQFNAITGLNGSGKSNVLDAIC...,1218,143057.5679,-0.841461,43.773563,0.067323,0.026273,0.006568,0.051724,0.118227,...,0.021346,0.088670,0.015599,0.041872,0.026273,0.054187,0.044335,0.041872,0.001642,0.040230
257549,MYIKQIRLKGFRTYKNETTIDFTRGINCIVGFNGSGKSNILLAIEF...,1193,141223.7597,-0.803101,46.522557,0.078793,0.019279,0.015088,0.051970,0.123219,...,0.020956,0.109807,0.004191,0.034367,0.025985,0.062028,0.031852,0.036044,0.000000,0.045264
257550,MVITLPKLKYALNALSPHISEETLNFHYNKHHAGYVNKLNTLIKDT...,198,22733.3478,-0.482828,30.806111,0.131313,0.070707,0.015152,0.050505,0.055556,...,0.015152,0.116162,0.035354,0.025253,0.010101,0.050505,0.040404,0.030303,0.040404,0.040404
257551,MMLNKKVVALCTLTLHLFCIFLCLGKEVRSEENGKIQDDAKKIVSE...,688,77645.7201,-0.627907,41.276323,0.081395,0.043605,0.014535,0.075581,0.068314,...,0.018895,0.109012,0.024709,0.011628,0.031977,0.117733,0.030523,0.049419,0.004360,0.043605
257552,MLNIIYVVSLILIKFIFYKECNNNNNYYLSNIELYNYKLRKRNRIL...,1341,154797.7810,-0.761670,34.211350,0.093214,0.030574,0.006711,0.063386,0.070843,...,0.017897,0.137957,0.024609,0.023863,0.022371,0.072334,0.037286,0.043251,0.003729,0.048471

In [28]:
df_prot_char.to_csv("./all_data_char_2.csv", index=False)

In [75]:
#251418
list_prot2 = list(analyze_prot)[79630:79637] 
error = df_clean_fin["sequence"].iloc[[79636]]
error
# result = [x.gravy() for x in list_prot2]

79924    MTFRKSFDCYDFYDRAKVGEKCTQDDWDLMKIPMKAMELKQKYGLD...
Name: sequence, dtype: object

In [ ]:
X_error = "MTFRKSFDCYDFYDRAKVGEKCTQDDWDLMKIPMKAMELKQKYGLDFKGEFIPTDKDMMEKLFKAGFEMLLECGIYCTDTHRIVKYTEDEIWDAINNVQKEFVLGTGRDAVNVRKRSVGDKAKPIVQGGPTGSPISEDVFMPVHMSYALEKEVDTIVNGVMTSVRGKSPIPKSPYEVLAAKTETRLIKNACAMAGRPGMGVOGPETSLSAQGNISADCTGGMTCTDSHEVSQLNELKIDLDAISVIAHYKGNSDIIMDEQMPIFGGYAGGIEETTIVDVATHINAVLMSSASWHLDGPVHIRWGSTNTRETLMIAGWACATISEFTDILSGNQYYPCAGPCTEMCLLEASAQSITDTASGREILSGVASAKGVVTDKTTGMEARMMGEVARATAGVEISEVNVILDKLVSLYEKNYASAPAGKTFQECYDVKTVTPTEEYMQVYDGARKKLEDLGLVF"

In [12]:
df = pd.read_csv("./all_data_Char.csv")
disordered_count = df.loc[df["label"]==1.0]
ordered_count = df.loc[df["label"]==0.0]
print(disordered_count.info())
print(ordered_count.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10937 entries, 0 to 251222
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sequence           10937 non-null  object
 1   seq_len            10937 non-null  int64
 2   molecular_weight   10937 non-null  float64
 3   hydrophobicity     10937 non-null  float64
 4   instability_index  10937 non-null  float64
 5   aromaticity        10937 non-null  float64
 6   label              10937 non-null  float64
dtypes: float64(5), int64(1), object(1)
memory usage: 683.6+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 240481 entries, 2366 to 251417
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   sequence           240481 non-null  object
 1   seq_len            240481 non-null  int64
 2   molecular_weight   240481 non-null  float64
 3   hydrophobicity     240481 non-null  float64
 4   instability_index  240481 non-null  float64
 5   aromaticity        240481 non-null  float64
 6   label              240481 non-null  float64
dtypes: float64(5), int64(1), object(1)
memory usage: 14.7+ MB
None

In [2]:
# data too big, so zipping instead
all_data = pd.read_csv("./all_data_char_2.csv")
compression_opts = dict(method='zip',
                        archive_name='all_data.csv')  
all_data.to_csv('all_data.zip', index=False,
          compression=compression_opts)