In [1]:
import json
import requests
import pandas as pd

In [40]:
rcsbdf = pd.read_table('/Users/kathe/Downloads/p-ai/pdb_seqresclean.txt',header=None, names=["ID", "type", "length", "name", "sequence"], sep=" ")

We got rid of everything with length <= 20 since those are mostly polypeptides which we don't want

In [45]:
rcsbdf
rcsbdf20 = rcsbdf[rcsbdf['length']> 20]

In [46]:
rcsbdf20

,ID,type,length,name,sequence
0,101m_A,protein,154.0,MYOGLOBIN,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...
1,102l_A,protein,165.0,T4!LYSOZYME,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSE...
2,102m_A,protein,154.0,MYOGLOBIN,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...
3,103l_A,protein,167.0,T4!LYSOZYME,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNSLDAAK...
4,103m_A,protein,154.0,MYOGLOBIN,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...
...,...,...,...,...,...
633940,9xia_A,protein,388.0,XYLOSE!ISOMERASE,MNYQPTPEDRFTFGLWTVGWQGRDPFGDATRRALDPVESVQRLAEL...
633941,9xim_A,protein,393.0,D-XYLOSE!ISOMERASE,SVQATREDKFSFGLWTVGWQARDAFGDATRTALDPVEAVHKLAEIG...
633942,9xim_B,protein,393.0,D-XYLOSE!ISOMERASE,SVQATREDKFSFGLWTVGWQARDAFGDATRTALDPVEAVHKLAEIG...
633943,9xim_C,protein,393.0,D-XYLOSE!ISOMERASE,SVQATREDKFSFGLWTVGWQARDAFGDATRTALDPVEAVHKLAEIG...
633944,9xim_D,protein,393.0,D-XYLOSE!ISOMERASE,SVQATREDKFSFGLWTVGWQARDAFGDATRTALDPVEAVHKLAEIG...

In [47]:
rcsbdf20.head(5)

,ID,type,length,name,sequence
0,101m_A,protein,154.0,MYOGLOBIN,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...
1,102l_A,protein,165.0,T4!LYSOZYME,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSE...
2,102m_A,protein,154.0,MYOGLOBIN,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...
3,103l_A,protein,167.0,T4!LYSOZYME,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNSLDAAK...
4,103m_A,protein,154.0,MYOGLOBIN,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...

Everything below this is stuff we are trying to do to flatten the json properly

In [48]:
#this didn't work
jsondf = pd.read_json("/Users/kathe/Downloads/p-ai/rcsb_pdb_sequence__007501-010000.json")
jsondf

     identifier                                               data   type
0          1HQ3  {'rcsb_id': '1HQ3', 'polymer_entities': [{'rcs...  entry
1          1HQ4  {'rcsb_id': '1HQ4', 'polymer_entities': [{'rcs...  entry
2          1HQ5  {'rcsb_id': '1HQ5', 'polymer_entities': [{'rcs...  entry
3          1HQ6  {'rcsb_id': '1HQ6', 'polymer_entities': [{'rcs...  entry
4          1HQ8  {'rcsb_id': '1HQ8', 'polymer_entities': [{'rcs...  entry
...         ...                                                ...    ...
2495       1KEP  {'rcsb_id': '1KEP', 'polymer_entities': [{'rcs...  entry
2496       1KEQ  {'rcsb_id': '1KEQ', 'polymer_entities': [{'rcs...  entry
2497       1KER  {'rcsb_id': '1KER', 'polymer_entities': [{'rcs...  entry
2498       1KET  {'rcsb_id': '1KET', 'polymer_entities': [{'rcs...  entry
2499       1KEU  {'rcsb_id': '1KEU', 'polymer_entities': [{'rcs...  entry

[2500 rows x 3 columns]

In [55]:
# Worked!

with open("/Users/kathe/Downloads/p-ai/rcsb_pdb_sequence__007501-010000.json") as in_file:
  file_contents = in_file.read()
  json_data = json.loads(file_contents)
  jsondf1 = pd.json_normalize(json_data, record_path=['data', 'polymer_entities'], meta=[['data', 'rcsb_id'], 'identifier'])

jsondf1

,rcsb_polymer_entity_container_identifiers.entity_id,rcsb_polymer_entity_container_identifiers.auth_asym_ids,rcsb_polymer_entity_container_identifiers.reference_sequence_identifiers,entity_poly.pdbx_seq_one_letter_code_can,entity_poly.rcsb_sample_sequence_length,entity_poly.type,rcsb_polymer_entity.formula_weight,data.rcsb_id,identifier
0,1,"[A, E]","[{'database_name': 'UniProt', 'database_access...",MSGRGKQGGKARAKAKSRSSRAGLQFPVGRVHRLLRKGNYAERVGA...,129,polypeptide(L),13.969,1HQ3,1HQ3
1,2,"[B, F]","[{'database_name': 'UniProt', 'database_access...",MPEPAKSAPAPKKGSKKAVTKTQKKGDKKRKKSRKESYSIYVYKVL...,126,polypeptide(L),13.953,1HQ3,1HQ3
2,3,"[C, G]","[{'database_name': 'UniProt', 'database_access...",MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,136,polypeptide(L),15.421,1HQ3,1HQ3
3,4,"[D, H]","[{'database_name': 'UniProt', 'database_access...",MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,103,polypeptide(L),11.394,1HQ3,1HQ3
4,1,"[A, C]","[{'database_name': 'UniProt', 'database_access...",DIVLTQSPTIMSVSPGEKVTLTCSASSSVSSNYVYWYQQKPGSSPK...,215,polypeptide(L),23.485,1HQ4,1HQ4
...,...,...,...,...,...,...,...,...,...
3800,1,"[A, B]","[{'database_name': 'UniProt', 'database_access...",MSQFKNIIVTGGAGFIGSNFVHYVYNNHPDVHVTVLDKLTYAGNKA...,348,polypeptide(L),38.982,1KEP,1KEP
3801,1,"[A, B]","[{'database_name': 'UniProt', 'database_access...",CATGTRQSPINIQWKDSVYDPQLAPLRVSYDAASCRYLWNTGYAFQ...,248,polypeptide(L),28.140,1KEQ,1KEQ
3802,1,"[A, B]","[{'database_name': 'UniProt', 'database_access...",MSQFKNIIVTGGAGFIGSNFVHYVYNNHPDVHVTVLDKLTYAGNKA...,348,polypeptide(L),38.982,1KER,1KER
3803,1,"[A, B]","[{'database_name': 'UniProt', 'database_access...",MSQFKNIIVTGGAGFIGSNFVHYVYNNHPDVHVTVLDKLTYAGNKA...,348,polypeptide(L),38.982,1KET,1KET
3804,1,"[A, B]","[{'database_name': 'UniProt', 'database_access...",MKILITGGAGFIGSAVVRHIIKNTQDTVVNIDKLTYAGNLESLSDI...,361,polypeptide(L),40.768,1KEU,1KEU

In [53]:
#this didn't work

with open("/Users/kathe/Downloads/p-ai/rcsb_pdb_sequence__007501-010000.json") as in_file:
  file_contents = in_file.read()
  json_data = json.loads(file_contents)
  jsondftest = pd.json_normalize(json_data, max_level=2, errors='ignore')



jsondftest

,identifier,type,data.rcsb_id,data.polymer_entities
0,1HQ3,entry,1HQ3,[{'rcsb_polymer_entity_container_identifiers':...
1,1HQ4,entry,1HQ4,[{'rcsb_polymer_entity_container_identifiers':...
2,1HQ5,entry,1HQ5,[{'rcsb_polymer_entity_container_identifiers':...
3,1HQ6,entry,1HQ6,[{'rcsb_polymer_entity_container_identifiers':...
4,1HQ8,entry,1HQ8,[{'rcsb_polymer_entity_container_identifiers':...
...,...,...,...,...
2495,1KEP,entry,1KEP,[{'rcsb_polymer_entity_container_identifiers':...
2496,1KEQ,entry,1KEQ,[{'rcsb_polymer_entity_container_identifiers':...
2497,1KER,entry,1KER,[{'rcsb_polymer_entity_container_identifiers':...
2498,1KET,entry,1KET,[{'rcsb_polymer_entity_container_identifiers':...
2499,1KEU,entry,1KEU,[{'rcsb_polymer_entity_container_identifiers':...

In [25]:
#this didn't work

with open("/Users/kathe/Downloads/p-ai/rcsb_pdb_sequence__007501-010000.json") as in_file:
  file_contents = in_file.read()
  json_data = json.loads(file_contents)
  jsondf2 = pd.json_normalize(json_data, max_level=1, record_path = ['data.polymer_entities'], errors='ignore')



display(jsondf2.head(10).dropna(axis=1))

KeyError: 'data.polymer_entities'

In [28]:
#this didn't work, it completely flattened the thing which we do not want

def flatten_json(y):
    out = {}

    def flatten(x, name=''):
        if type(x) is dict:
            for a in x:
                flatten(x[a], name + a + '_')
        elif type(x) is list:
            i = 0
            for a in x:
                flatten(a, name + str(i) + '_')
                i += 1
        else:
            out[name[:-1]] = x

    flatten(y)
    return out

In [29]:
#this didn't work

with open("/Users/kathe/Downloads/p-ai/rcsb_pdb_sequence__007501-010000.json") as in_file:
  file_contents = in_file.read()
  json_data = json.loads(file_contents)
flat = flatten_json(json_data)
flatdf = pd.json_normalize(flat)
flatdf

In [38]:
#this didn't work, attempted to flatten only inner elements

def flatten(x, name=''):
    out = {}
    if type(x) is dict:
        for a in x:
            flatten(x[a], name + a + '_')
    elif type(x) is list:
        i = 0
        for a in x:
            flatten(a, name + str(i) + '_')
            i += 1
    else:
        out[name[:-1]] = x
    return out

In [39]:
#this didn't work

with open("/Users/kathe/Downloads/p-ai/rcsb_pdb_sequence__007501-010000.json") as in_file:
  file_contents = in_file.read()
  json_data = json.loads(file_contents)
dic_flattened = [flatten(d) for d in json_data]
dfgood = df = pd.DataFrame(dic_flattened)
dfgood

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[2500 rows x 0 columns]